version: "3"

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php worker.php"

temporal:
  address: ${TEMPORAL_HOST:-localhost}:${TEMPORAL_PORT:-7233}
  activities:
    num_workers: 4

logs:
  level: info
  mode: development
